In [2]:
import sklearn
import pandas as pd

print(sklearn.__version__)

0.23.2


In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [5]:
## 붓꽃 데이터 로딩
iris = load_iris()

## iris.data는 iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있음.
iris_data = iris.data

## iris.target은 iris 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있음.
iris_label = iris.target
print(f'iris target 값 : {iris_label}')
print(f'iris target 명 : {iris.target_names}')

## iris 데이터 세트를 자세히 보기위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target 값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 : ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

setosa : 0 , versicolor : 1 , virginica : 2

### 테스트 데이터와 학습 데이터로 분할
train_test_split()

X_train : 학습용 피처 데이터 세트

X_test : 테스트용 피처 데이터 세트

y_train : 학습용 레이블 데이터 세트

y_test : 테스트용 레이블 데이터 세트

In [18]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, 
                                                   test_size=0.2, random_state=9)
                                                ## iris_data = 데이터 리스트 (피처 데이터 세트)
                                                ## iris_label = 데이터 컬럼 (레이블 데이터 세트)
## random_state = 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어지는 난수발생 값
## 값을 지정하지 않으면 수행할 때마다 다른 데이터 발생

In [19]:
X_test, X_test.shape, y_test, y_test.shape

(array([[7.7, 3. , 6.1, 2.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.7, 3. , 5.2, 2.3],
        [6.5, 3. , 5.2, 2. ],
        [5. , 2. , 3.5, 1. ],
        [4.9, 3.6, 1.4, 0.1],
        [5. , 3.4, 1.6, 0.4],
        [4.6, 3.1, 1.5, 0.2],
        [6.6, 3. , 4.4, 1.4],
        [4.9, 3.1, 1.5, 0.1],
        [5. , 3. , 1.6, 0.2],
        [6.1, 2.8, 4.7, 1.2],
        [5.1, 2.5, 3. , 1.1],
        [5.6, 2.7, 4.2, 1.3],
        [5.1, 3.4, 1.5, 0.2],
        [5.5, 2.4, 3.7, 1. ],
        [5.4, 3.4, 1.5, 0.4],
        [5.7, 2.8, 4.5, 1.3],
        [5.8, 2.7, 5.1, 1.9],
        [4.6, 3.2, 1.4, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [5.2, 3.5, 1.5, 0.2],
        [6.4, 2.7, 5.3, 1.9],
        [5.4, 3.4, 1.7, 0.2],
        [7.7, 2.6, 6.9, 2.3],
        [5.5, 2.5, 4. , 1.3],
        [5. , 3.5, 1.6, 0.6],
        [6.7, 3.3, 5.7, 2.5],
        [4.4, 2.9, 1.4, 0.2],
        [6.4, 3.1, 5.5, 1.8]]),
 (30, 4),
 array([2, 1, 2, 2, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0,
        2, 0, 

In [20]:
# DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(random_state=9)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=9)

In [21]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)
pred

array([2, 1, 2, 2, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0,
       2, 0, 2, 1, 0, 2, 0, 2])

In [22]:
from sklearn.metrics import accuracy_score

Score = accuracy_score(y_test, pred)
print(f'예측 정확도 : {round(Score, 4)}')

예측 정확도 : 1.0
