In [89]:
import numpy as np

### 18p

In [3]:
seq_array = np.arange(15)
seq_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
zero_arr = np.zeros((3, 2), dtype='int32')
zero_arr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [10]:
one_arr = np.ones((3,2))   # default : float64
one_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
print(seq_array.reshape(3, 5))
print(seq_array.reshape(5, 3))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [16]:
array_1 = np.arange(8)
array_2 = array_1.reshape(2, 2, 2)

print(array_2.tolist())                 # 1차원 -> 3차원
print(array_2.reshape(-1, 1).tolist())  # 3차원 -> 2차원
print(array_1.reshape(-1, 1).tolist())  # 1차원 -> 2차원

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]


### numpy 인덱싱 (23p)

In [19]:
array_1 = np.arange(start=1, stop=10)
print(array_1)

array_1[2], type(array_1[2]), array_1[-2]

[1 2 3 4 5 6 7 8 9]


(3, numpy.int32, 8)

In [21]:
## 값 수정 가능
array_1[3] = 10
array_1

array([ 1,  2,  3, 10,  5,  6,  7,  8,  9])

In [23]:
array_1 = np.arange(1, 10)
array_1 = array_1.reshape(3,3)
print(array_1.tolist())

print(array_1[1, 1], array_1[2, 2])  # 2행 2열 / 3행 3열

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
5 9


In [24]:
array_1[1,:]  # 2행의 정보

array([4, 5, 6])

In [30]:
array_1 = np.arange(1, 9)

print(array_1)
print(array_1[3:7])
print(array_1[:5])
print(array_1[6:])

[1 2 3 4 5 6 7 8]
[4 5 6 7]
[1 2 3 4 5]
[7 8]


In [35]:
print(array_1.reshape(2, 2, 2).tolist())
print(array_1.reshape(2, 2, 2)[:,0].tolist())  # 한 차원 축소

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[[1, 2], [5, 6]]


### 팬시 인덱싱 (29p)
리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식.

In [2]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]     # 1행+2행 , 3열
print(array3.tolist())

array4 = array2d[[0, 1], 0:2]   # 1행+2행 , 1열+2열
# array4 = array2d[[0, 1], [0, 1]]
print(array4.tolist())

array5 = array2d[[0, 1]]        # 1행+2행
print(array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [3]:
array1d[[6, 7, 8]]  # 인덱스를 넣으면 인덱스에 해당하는 값 반환

array([7, 8, 9])

### argsort() (35p)
정렬된 행렬의 인덱스를 반환하기

In [6]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(org_array)
print(sort_indices)   # 오름차순 정렬했을 때의 인덱스

sort_indices_1 = np.argsort(org_array)[::-1]
print(sort_indices_1) # 내림차순 정렬했을 때의 인덱스

[3 1 9 5]
[1 0 3 2]
[2 3 0 1]


In [9]:
name_array = np.array(['A', 'B', 'C', 'D', 'E'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)   # 오름차순 정렬했을 때 인덱스
print(sort_indices_asc)
print(name_array[sort_indices_asc])
print(score_array[sort_indices_asc])

[0 2 4 1 3]
['A' 'C' 'E' 'B' 'D']
[78 84 88 95 98]


### 행렬 내적
np.dot()

In [4]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
B = np.array([[7, 8], 
              [9, 10], 
              [11, 12]])

np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In [5]:
A.T, B.T

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[ 7,  9, 11],
        [ 8, 10, 12]]))

### ndarray, list, dict를 DataFrame으로 변환하기 (49p)

In [91]:
import pandas as pd

In [11]:
col_name_1 = ['col_1']
list_1 = [1, 2, 3]
array_1 = np.array(list_1)
print(array_1.shape)

df_list_1 = pd.DataFrame(list_1, columns = col_name_1)   # 1차원 리스트로 만든 DF
print(df_list_1)

(3,)
   col_1
0      1
1      2
2      3


In [12]:
df_array_1 = pd.DataFrame(array_1, columns=col_name_1)   # 1차원 ndarray로 만든 DF
print(df_array_1)

   col_1
0      1
1      2
2      3


#### 2차원의 DataFrame

In [14]:
col_name_2 = ['col1', 'col2', 'col3']

list_2 = [[1, 2, 3],
         [ 4, 5, 6]]

array_2 = np.array(list_2)
print(array_2, array_2.shape)

df_list_2 = pd.DataFrame(list_2, columns=col_name_2)
df_array_2 = pd.DataFrame(array_2, columns=col_name_2)

print(df_list_2)
print(df_array_2)

[[1 2 3]
 [4 5 6]] (2, 3)
   col1  col2  col3
0     1     2     3
1     4     5     6
   col1  col2  col3
0     1     2     3
1     4     5     6


#### DataFrame에서 ndarray로의 변환

In [16]:
array_3 = df_list_2.values

print(type(array_3), array_3.shape)

<class 'numpy.ndarray'> (2, 3)


#### DataFrame에서 list, dict로의 변환

In [17]:
print(df_list_2)

list_3 = df_list_2.values.tolist()   # 리스트
print(type(list_3), list_3)

dict_3 = df_list_2.to_dict('list')   # 딕셔너리
print(type(dict_3), dict_3)

   col1  col2  col3
0     1     2     3
1     4     5     6
<class 'list'> [[1, 2, 3], [4, 5, 6]]
<class 'dict'> {'col1': [1, 4], 'col2': [2, 5], 'col3': [3, 6]}


In [90]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

In [21]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [92]:
df_1 = titanic.copy()
df_1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [23]:
df_1.drop(['deck', 'embark_town'], axis=1)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male alive  alone  
0      man        True    no  False  
1    woman       False   yes  False  
2    woman       False   yes   True  
3    woman       False   yes  False  
4      man        True    no   True  
..     ...         ...   ...    ...  
886    man        True    no   True  
887  woman       False   yes   True  
888  woman       False    no  False  
889    man        True   yes   True  
890    man        True    no   True  

[891 rows x 13 columns]

In [29]:
df_1.drop(range(4))

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
4           0       3    male  35.0      0      0   8.0500        S   Third   
5           0       3    male   NaN      0      0   8.4583        Q   Third   
6           0       1    male  54.0      0      0  51.8625        S   First   
7           0       3    male   2.0      3      1  21.0750        S   Third   
8           1       3  female  27.0      0      2  11.1333        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
4      man        True  NaN  Southampton    no   True  
5      man        True  NaN   Queenstown    no   True  
6      man        True    E  Southampton    no   True  
7    child       False  NaN  Southampton    no  False  
8    woman       False  NaN  Southampton   yes  False  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[887 rows x 15 columns]

In [37]:
df_1['fare'].max(), df_1.fare.sum(), 
df_1.fare.head(3), (df_1.fare + 3).head(3)

(0     7.2500
 1    71.2833
 2     7.9250
 Name: fare, dtype: float64,
 0    10.2500
 1    74.2833
 2    10.9250
 Name: fare, dtype: float64)

### reset_index() (60p)
데이터의 순서를 정렬한 후 새롭게 인덱스를 재 지정

In [45]:
cnt_val = titanic['pclass'].value_counts()
print(cnt_val)

new_cnt_val = cnt_val.reset_index()
new_cnt_val, type(new_cnt_val)

3    491
1    216
2    184
Name: pclass, dtype: int64


(   index  pclass
 0      3     491
 1      1     216
 2      2     184,
 pandas.core.frame.DataFrame)

In [44]:
cnt_val.reset_index(drop=True), type(cnt_val.reset_index(drop=True))

(0    491
 1    216
 2    184
 Name: pclass, dtype: int64,
 pandas.core.series.Series)

In [49]:
df_1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [50]:
df_1.iloc[0:4, 1:6]

pclass     sex   age  sibsp  parch
0       3    male  22.0      1      0
1       1  female  38.0      1      0
2       3  female  26.0      0      0
3       1  female  35.0      1      0

In [51]:
df_1.loc[0:4, 'pclass': 'fare']

pclass     sex   age  sibsp  parch     fare
0       3    male  22.0      1      0   7.2500
1       1  female  38.0      1      0  71.2833
2       3  female  26.0      0      0   7.9250
3       1  female  35.0      1      0  53.1000
4       3    male  35.0      0      0   8.0500

In [53]:
df_1[(df_1['age']>60) & (df_1['pclass']==1) & (df_1['sex']=='female')]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
275         1       1  female  63.0      1      0  77.9583        S  First   
829         1       1  female  62.0      0      0  80.0000      NaN  First   

       who  adult_male deck  embark_town alive  alone  
275  woman       False    D  Southampton   yes  False  
829  woman       False    B          NaN   yes   True

In [77]:
pd.set_option('display.max_rows', 20)

In [78]:
df_1.sort_values(['pclass', 'fare'], ascending=False)

survived  pclass     sex   age  sibsp  parch   fare embarked  class  \
159         0       3    male   NaN      8      2  69.55        S  Third   
180         0       3  female   NaN      8      2  69.55        S  Third   
201         0       3    male   NaN      8      2  69.55        S  Third   
324         0       3    male   NaN      8      2  69.55        S  Third   
792         0       3  female   NaN      8      2  69.55        S  Third   
..        ...     ...     ...   ...    ...    ...    ...      ...    ...   
263         0       1    male  40.0      0      0   0.00        S  First   
633         0       1    male   NaN      0      0   0.00        S  First   
806         0       1    male  39.0      0      0   0.00        S  First   
815         0       1    male   NaN      0      0   0.00        S  First   
822         0       1    male  38.0      0      0   0.00        S  First   

       who  adult_male deck  embark_town alive  alone  
159    man        True  NaN  Southampton    no  False  
180  woman       False  NaN  Southampton    no  False  
201    man        True  NaN  Southampton    no  False  
324    man        True  NaN  Southampton    no  False  
792  woman       False  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
263    man        True    B  Southampton    no   True  
633    man        True  NaN  Southampton    no   True  
806    man        True    A  Southampton    no   True  
815    man        True    B  Southampton    no   True  
822    man        True  NaN  Southampton    no   True  

[891 rows x 15 columns]

### aggregation 함수 적용

In [80]:
df_1.groupby('pclass')['age'].max()

pclass
1    80.0
2    70.0
3    74.0
Name: age, dtype: float64

In [82]:
df_1.groupby('pclass')['age', 'fare'].agg([max, min])

<ipython-input-82-c541ca4fb46b>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_1.groupby('pclass')['age', 'fare'].agg([max, min])


age            fare     
         max   min       max  min
pclass                           
1       80.0  0.92  512.3292  0.0
2       70.0  0.67   73.5000  0.0
3       74.0  0.42   69.5500  0.0

In [83]:
agg_format = {'age':'max', 'sibsp':'sum', 'fare':'mean'}

df_1.groupby('pclass').agg(agg_format)

age  sibsp       fare
pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

나이가 15세 이하이면 child, 15세~60세 사이는 adult, 61세 이상은 elderly로 분류

In [93]:
df_1['age_cat'] = df_1['age'].apply(lambda x: 'Child' if x<=15 else 
                                    ('Adult' if x<=60 else 'Elderly'))
df_1['age_cat'].value_counts()

Adult      609
Elderly    199
Child       83
Name: age_cat, dtype: int64

In [96]:
# titanic_df = pd.read_csv('titanic_train.csv')

titanic_boolean = df_1[df_1['age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
33          0       2    male  66.0      0      0  10.5000        S  Second   
54          0       1    male  65.0      0      1  61.9792        C   First   
96          0       1    male  71.0      0      0  34.6542        C   First   
116         0       3    male  70.5      0      0   7.7500        Q   Third   
170         0       1    male  61.0      0      0  33.5000        S   First   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
630         1       1    male  80.0      0      0  30.0000        S   First   
672         0       2    male  70.0      0      0  10.5000        S  Second   
745         0       1    male  70.0      1      1  71.0000        S   First   
829         1       1  female  62.0      0      0  80.0000      NaN   First   
851         0       3    male  74.0      0      0   7.7750        S   Third   

       who  adult_male deck  embark_town alive  alone  age_cat  
33     man        True  NaN  Southampton    no   True  Elderly  
54     man        True    B    Cherbourg    no  False  Elderly  
96     man        True    A    Cherbourg    no   True  Elderly  
116    man        True  NaN   Queenstown    no   True  Elderly  
170    man        True    B  Southampton    no   True  Elderly  
..     ...         ...  ...          ...   ...    ...      ...  
630    man        True    A  Southampton   yes   True  Elderly  
672    man        True  NaN  Southampton    no   True  Elderly  
745    man        True    B  Southampton    no  False  Elderly  
829  woman       False    B          NaN   yes   True  Elderly  
851    man        True  NaN  Southampton    no   True  Elderly  

[22 rows x 16 columns]

In [98]:
df_1['Child_Adult'] = df_1['age'].apply(lambda x: 'Child' if x <= 15 else 'Adult')
df_1[['age','Child_Adult']].head(8)

age Child_Adult
0  22.0       Adult
1  38.0       Adult
2  26.0       Adult
3  35.0       Adult
4  35.0       Adult
5   NaN       Adult
6  54.0       Adult
7   2.0       Child